from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import time

draft_model_name = "gpt2"         # 124M parameters - draft model
target_model_name = "gpt2-medium"  # 345M parameters - target model

# Load tokenizer (same for both models)
tokenizer = AutoTokenizer.from_pretrained(target_model_name)

# Draft model
draft_model = AutoModelForCausalLM.from_pretrained(
    draft_model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

# Target model
target_model = AutoModelForCausalLM.from_pretrained(
    target_model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

print(f"Draft model: {sum(p.numel() for p in draft_model.parameters()):,} parameters")
print(f"Target model: {sum(p.numel() for p in target_model.parameters()):,} parameters")
print(f"Ratio: {sum(p.numel() for p in target_model.parameters()) / sum(p.numel() for p in draft_model.parameters()):.1f}x")


def draft_tokens(draft_model, input_ids, K=5, temperature=1.0):
    """
    Generate K draft tokens using the small model.
    """
    draft_ids = []
    draft_probs = []
    current_input = input_ids.clone()

    with torch.no_grad():
        for _ in range(K):
            outputs = draft_model(current_input)
            next_token_logits = outputs.logits[:, -1, :]

            probs = torch.softmax(next_token_logits / temperature, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)

            draft_ids.append(next_token)
            token_prob = probs.gather(-1, next_token)
            draft_probs.append(token_prob)

            current_input = torch.cat([current_input, next_token], dim=-1)

    # Return as 2D tensors [1, K]
    draft_ids = torch.cat(draft_ids, dim=-1)      # [1, K]
    draft_probs = torch.cat(draft_probs, dim=-1)  # [1, K]

    return draft_ids, draft_probs


def verify_tokens(target_model, input_ids, draft_ids, temperature=1.0):
    """
    Verify all draft tokens in one forward pass.

    The key insight: we feed [input_ids + draft_ids] to the target model
    and get probability distributions for ALL positions at once.
    """

    # Ensure draft_ids is 2D
    if draft_ids.dim() == 1:
        draft_ids = draft_ids.unsqueeze(0)

    # Concatenate original input with draft tokens
    full_sequence = torch.cat([input_ids, draft_ids], dim=-1)

    with torch.no_grad():
        outputs = target_model(full_sequence)
        logits = outputs.logits

    # We need probabilities for positions where draft tokens were placed
    # If input_ids has length N and draft_ids has length K,
    # we want logits at positions N-1, N, N+1, ..., N+K-1
    # (position i predicts token i+1)

    K = draft_ids.shape[-1]
    start_pos = input_ids.shape[-1] - 1

    target_logits = logits[:, start_pos:start_pos + K + 1, :]
    target_probs = torch.softmax(target_logits / temperature, dim=-1)

    # Get probability distributions for each draft position + one extra
    return target_probs


def acceptance_sampling(draft_ids, draft_probs, target_probs, device):
    """
    Decide which draft tokens to accept using rejection sampling.

    This implements the core speculative decoding acceptance criterion:
    - Accept draft token with probability min(1, p(x)/q(x))
    - If rejected, sample from the residual distribution to correct bias
    - p(x) Probability of the target model for token x
    - q(x) Probability of the draft model for token x

    Args:
        draft_ids: Token IDs generated by draft model [1, K]
        draft_probs: Probabilities assigned by draft model [1, K]
        target_probs: Probabilities from target model [1, K+1, vocab_size]
        device: CUDA device for tensor operations

    Returns:
        accepted_ids: Tensor of accepted token IDs
        n_accepted: Number of tokens accepted (excluding bonus)
    """
    # Ensure correct shapes [1, K]
    if draft_ids.dim() == 1:
        draft_ids = draft_ids.unsqueeze(0)
    if draft_probs.dim() == 1:
        draft_probs = draft_probs.unsqueeze(0)

    K = draft_ids.shape[-1]  # Number of draft tokens
    accepted_ids = []

    # Iterate through each draft token sequentially
    for i in range(K):
        draft_token = draft_ids[:, i:i+1]  # [1, 1] - current draft token
        q_prob = draft_probs[:, i]          # [1] - draft model's probability q(x)

        # Target model's probability for this specific token: p(x)
        p_prob = target_probs[:, i, :].gather(-1, draft_token).squeeze(-1)  # [1]

        # Acceptance probability: min(1, p(x)/q(x))
        # This ensures we accept more often when target agrees with draft
        acceptance_ratio = (p_prob / (q_prob + 1e-10)).clamp(max=1.0)

        # Random acceptance decision using uniform random number
        if torch.rand(1, device=device).item() < acceptance_ratio.item():
            # Token accepted - add to our sequence
            accepted_ids.append(draft_token)
        else:
            # Token rejected - sample from residual distribution
            # The residual distribution corrects for the draft model's bias
            p_dist = target_probs[:, i, :]  # Target's full distribution
            q_dist = torch.zeros_like(p_dist)
            q_dist.scatter_(-1, draft_token, q_prob.unsqueeze(-1))

            # Residual distribution: max(0, p - q) normalized
            # This samples tokens that target prefers but draft underweighted
            residual = torch.clamp(p_dist - q_dist, min=0)
            residual_sum = residual.sum(dim=-1, keepdim=True)

            if residual_sum.item() > 1e-10:
                # Sample from normalized residual distribution
                residual = residual / residual_sum
                correction = torch.multinomial(residual, num_samples=1)
            else:
                # Fallback: sample directly from target distribution
                correction = torch.multinomial(p_dist, num_samples=1)

            accepted_ids.append(correction)
            break  # Stop here - all following draft tokens are now invalid

    n_accepted = len(accepted_ids)

    # Bonus token: if we accepted all K tokens, we get a free extra token
    # This is the key efficiency gain - we verified K tokens but get K+1
    if n_accepted == K:
        bonus_token = torch.multinomial(target_probs[:, K, :], num_samples=1)
        accepted_ids.append(bonus_token)

    # Concatenate all accepted tokens into single tensor
    if accepted_ids:
        accepted_ids = torch.cat(accepted_ids, dim=-1)  # [1, n]
    else:
        accepted_ids = torch.tensor([[]], dtype=torch.long, device=device)

    return accepted_ids, n_accepted


def speculative_generate(
    prompt: str,
    draft_model,
    target_model,
    tokenizer,
    max_new_tokens: int = 50,
    K: int = 5,
    temperature: float = 1.0
):
    """
    Generate text using speculative decoding.
    """
    device = next(draft_model.parameters()).device
    input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)
    generated = input_ids.clone()

    total_draft_tokens = 0
    total_accepted = 0
    total_generated = 0

    while total_generated < max_new_tokens:
        # Phase 1: Draft K tokens
        draft_ids, draft_probs = draft_tokens(
            draft_model, generated, K=K, temperature=temperature
        )
        total_draft_tokens += K

        # Phase 2: Verify with target model
        target_probs = verify_tokens(
            target_model, generated, draft_ids, temperature=temperature
        )

        # Phase 3: Accept/Reject
        accepted_ids, n_accepted = acceptance_sampling(
            draft_ids, draft_probs, target_probs, device
        )

        num_new = accepted_ids.shape[-1] if accepted_ids.numel() > 0 else 0
        total_accepted += num_new
        total_generated += num_new

        print(f"Drafted {K} tokens, accepted {n_accepted} (+bonus = {num_new}) tokens.")
        print(f"Total generated: {total_generated}/{max_new_tokens}")

        # Append accepted tokens
        if accepted_ids.numel() > 0:
            if accepted_ids.dim() == 1:
                accepted_ids = accepted_ids.unsqueeze(0)
            generated = torch.cat([generated, accepted_ids], dim=-1)

        # Check for EOS
        if tokenizer.eos_token_id is not None:
            if tokenizer.eos_token_id in accepted_ids:
                print("EOS token found!")
                break

    output_text = tokenizer.decode(generated[0], skip_special_tokens=True)
    acceptance_rate = total_accepted / total_draft_tokens if total_draft_tokens > 0 else 0

    return output_text, acceptance_rate


def compare_generation_speed(prompt, max_new_tokens=50):
    """
    Compare standard generation vs speculative decoding.
    """
    print(f"Prompt: {prompt}\n")
    print("=" * 60)

    device = next(target_model.parameters()).device
    input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)

    # Warmup (important for CUDA)
    print("Warming up...")
    with torch.no_grad():
        _ = target_model(input_ids[:, :5] if input_ids.shape[1] > 5 else input_ids)
        _ = draft_model(input_ids[:, :5] if input_ids.shape[1] > 5 else input_ids)
    torch.cuda.synchronize()
    print("Warmup complete.\n")

    # Standard generation
    torch.cuda.synchronize()
    start = time.time()
    with torch.no_grad():
        standard_output = target_model.generate(
            input_ids,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=1.0,
            pad_token_id=tokenizer.eos_token_id
        )
    torch.cuda.synchronize()
    standard_time = time.time() - start
    standard_text = tokenizer.decode(standard_output[0], skip_special_tokens=True)

    print(f"STANDARD DECODING (target model only)")
    print(f"Time: {standard_time:.2f}s")
    print(f"Tokens/sec: {max_new_tokens / standard_time:.1f}")
    print(f"Output: {standard_text[:200]}...")
    print()

    # Speculative decoding
    torch.cuda.synchronize()
    start = time.time()
    spec_text, acceptance_rate = speculative_generate(
        prompt, draft_model, target_model, tokenizer,
        max_new_tokens=max_new_tokens, K=5
    )
    torch.cuda.synchronize()
    spec_time = time.time() - start

    print(f"\nSPECULATIVE DECODING (draft + target)")
    print(f"Time: {spec_time:.2f}s")
    print(f"Tokens/sec: {max_new_tokens / spec_time:.1f}")
    print(f"Acceptance rate: {acceptance_rate:.1%}")
    print(f"Speedup: {standard_time / spec_time:.2f}x")
    print(f"Output: {spec_text[:200]}...")


# Run the comparison
compare_generation_speed(
    "The future of artificial intelligence will",
    max_new_tokens=20
)